version: 2.1

scalar-1: &working_dir ~/repo

executors:
  docker-circleci:
    parameters:
      node:
        type: string
        default: "10.12"
    working_directory: *working_dir
    docker:
      - image: "circleci/node:<< parameters.node >>-stretch-browsers"

commands:
  parameters:
    name:
      type: string
  clone:
    steps:
      - git clone https://github.com/aurelia/<< parameters.name >>
      - cd << parameters.name >>

jobs:
  polyfills:
    executor: docker-circleci
    steps:
      - checkout:
        name: polyfills

workflows:
  build:
    jobs:
      - polyfills
      