description: # The purpose of this orb

orbs:
  aurelia_v1_tests:
    executors:
      docker_circleci:
        docker:
          - image: circleci/node:10.12-stretch-browsers
    commands:
      clone_install_build_test:
        steps:
          - run: git clone https://github.com/aurelia/polyfills
          - run:
              name: Install
              command: |
                cd polyfills>
                npm ci
                npm i jspm
                ./node_modules/.bin/jspm install
                ./node_modules/.bin/gulp build
                ./node_modules/.bin/karma start --single-run
                ./node_modules/.bin/gulp prepare-release
    jobs:
      run_all:
        executor: docker_circleci
        steps:
          - clone_install_build_test

version: 2.1
workflows:
  main:
    jobs:
      - aurelia_v1_tests/run_all
