version: 2.1

scalar-1: &working_dir ~/repo

executors:
  docker-circleci:
    parameters:
      node:
        type: string
        default: "10.12"
    working_directory: *working_dir
    docker:
      - image: "circleci/node:<< parameters.node >>-stretch-browsers"

commands:
  clone_repo:
    parameters:
      repo:
        type: string
    steps:
      - run: git clone https://github.com/aurelia/<< parameters.repo >>
      - run:
          name: Install
          command: |
            cd << parameters.repo >>
            npm ci
            
  build_gulp:
    parameters:
      repo:
        type: string
    steps:
      - run:
          name: Build
          command: |
            cd << parameters.repo >>
            npm i jspm
            ./node_modules/.bin/jspm install
            ./node_modules/.bin/gulp build
            ./node_modules/.bin/karma start --single-run
            ./node_modules/.bin/gulp prepare-release
            
  build_npm:
    parameters:
      repo:
        type: string
    steps:
      - run:
          name: Build
          command: |
            cd << parameters.repo >>
            npm run build
            npm run test
            npm run prepare-release
            

jobs:
  polyfills:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: polyfills
      - build_gulp:
          repo: polyfills
  pal:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: pal
      - build_gulp:
          repo: pal
  pal-browser:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: pal-browser
      - build_gulp:
          repo: pal-browser
  pal-nodejs:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: pal-nodejs
      - build_gulp:
          repo: pal-nodejs
  logging:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: logging
      - build_gulp:
          repo: logging
  logging-console:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: logging-console
      - build_gulp:
          repo: logging-console
  metadata:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: metadata
      - build_gulp:
          repo: metadata
  dependency-injection:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: dependency-injection
      - build_gulp:
          repo: dependency-injection
  history:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: history
      - build_gulp:
          repo: history
  history-browser:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: history-browser
      - build_gulp:
          repo: history-browser
  path:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: path
      - build_gulp:
          repo: path
  http-client:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: http-client
      - build_gulp:
          repo: http-client
  fetch-client:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: fetch-client
      - build_gulp:
          repo: fetch-client
  loader:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: loader
      - build_gulp:
          repo: loader
  loader-default:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: loader-default
      - build_gulp:
          repo: loader-default
  event-aggregator:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: event-aggregator
      - build_gulp:
          repo: event-aggregator
  task-queue:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: task-queue
      - build_gulp:
          repo: task-queue
  route-recognizer:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: route-recognizer
      - build_gulp:
          repo: route-recognizer
  binding:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: binding
      - build_gulp:
          repo: binding
  router:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: router
      - build_npm:
          repo: router
  templating:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: templating
      - build_gulp:
          repo: templating
  templating-binding:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: templating-binding
      - build_gulp:
          repo: templating-binding
  templating-resources:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: templating-resources
      - build_gulp:
          repo: templating-resources
  templating-router:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: templating-router
      - build_npm:
          repo: templating-router
  framework:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: framework
      - build_gulp:
          repo: framework
  bootstrapper:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: bootstrapper
      - build_gulp:
          repo: bootstrapper
  animator-css:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: animator-css
      - build_gulp:
          repo: animator-css
  animator-velocity:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: animator-velocity
      - build_gulp:
          repo: animator-velocity
  i18n:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: i18n
      - build_npm:
          repo: i18n
  validation:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: validation
      - build_npm:
          repo: validation
  dialog:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: dialog
      - build_npm:
          repo: dialog
  ui-virtualization:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: ui-virtualization
      - build_npm:
          repo: ui-virtualization
  store:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: store
      - build_npm:
          repo: store
  script:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: script
      - build_npm:
          repo: script

workflows:
  build:
    jobs:
      - polyfills
      - pal
      - logging
      - logging-console
      - metadata
      - history
      - history-browser
      - path
      - http-client
      - fetch-client
      - loader
      - loader-default
      - event-aggregator
      - task-queue
      - route-recognizer
      - binding
      - templating
      - templating-binding
      - bootstrapper
      - i18n
      - validation
