description: Aurelia V1 tests

orbs:
  aurelia_v1_tests:
    jobs:
      run_all:
        steps:
          - run: echo "test"
          
version: 2.1
workflows:
  run_aurelia_v1_tests:
    jobs:
      - aurelia_v1_tests/run_all
