version: 2.1

orbs:
  orb-tools: circleci/orb-tools@2.0.0

workflows:
  build_test_deploy:
    jobs:
      - orb-tools/publish:
          orb-path: src/common.yml
          orb-ref: aurelia/common@0.0.7
          publish-token-variable: "$CIRCLECI_DEV_API_TOKEN"
          validate: true
      - orb-tools/publish:
          orb-path: src/v1.yml
          orb-ref: aurelia/v1@0.0.13
          publish-token-variable: "$CIRCLECI_DEV_API_TOKEN"
          validate: true

