version: 2.1

orbs:
  aurelia_v1_tests:
    jobs:
      run_all:
        parameters:
          repo_name:
            type: string
      executor: docker-circleci
      steps:
        - clone_install_build_test:
            repo_name: << parameters.repo_name >>
    commands:
      clone_install_build_test:
        parameters:
          repo_name:
            type: string
        steps:
          - run: git clone https://github.com/aurelia/<< parameters.repo_name >>
          - run:
              name: Install
              command: |
                cd << parameters.repo_name >>
                npm ci
                npm i jspm
                ./node_modules/.bin/jspm install
                ./node_modules/.bin/gulp build
                ./node_modules/.bin/karma start --single-run
                ./node_modules/.bin/gulp prepare-release
    executors:
      docker-circleci:
        node_version:
          type: string
          default: "10.12"
        working_directory: "~/repo"
        docker:
          - image: "circleci/node:<< parameters.node_version >>-stretch-browsers"

jobs:
  polyfills:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: polyfills
      - build_gulp:
          repo: polyfills
  pal:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: pal
      - build_gulp:
          repo: pal
  logging:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: logging
      - build_gulp:
          repo: logging
  logging-console:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: logging-console
      - build_gulp:
          repo: logging-console
  metadata:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: metadata
      - build_gulp:
          repo: metadata
  dependency-injection:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: dependency-injection
      - build_gulp:
          repo: dependency-injection
  history:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: history
      - build_gulp:
          repo: history
  history-browser:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: history-browser
      - build_gulp:
          repo: history-browser
  path:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: path
      - build_gulp:
          repo: path
  http-client:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: http-client
      - build_gulp:
          repo: http-client
  fetch-client:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: fetch-client
      - build_npm:
          repo: fetch-client
  loader:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: loader
      - build_gulp:
          repo: loader
  loader-default:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: loader-default
      - build_gulp:
          repo: loader-default
  event-aggregator:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: event-aggregator
      - build_gulp:
          repo: event-aggregator
  task-queue:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: task-queue
      - build_gulp:
          repo: task-queue
  route-recognizer:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: route-recognizer
      - build_gulp:
          repo: route-recognizer
  binding:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: binding
      - build_gulp:
          repo: binding
  templating:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: templating
      - build_gulp:
          repo: templating
  templating-binding:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: templating-binding
      - build_gulp:
          repo: templating-binding
  framework:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: framework
      - build_gulp:
          repo: framework
  bootstrapper:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: bootstrapper
      - build_gulp:
          repo: bootstrapper
  i18n:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: i18n
      - build_npm:
          repo: i18n
  validation:
    executor: docker-circleci
    steps:
      - clone_repo:
          repo: validation
      - build_npm:
          repo: validation

workflows:
  build:
    jobs:
      - aurelia_v1_tests/run_all:
          name: "polyfills"
          repo_name: "polyfills"
      - aurelia_v1_tests/run_all:
          name: "pal"
          repo_name: "pal"
      - aurelia_v1_tests/run_all:
          name: "logging"
          repo_name: "logging"
      - aurelia_v1_tests/run_all:
          name: "logging-console"
          repo_name: "logging-console"
      - aurelia_v1_tests/run_all:
          name: "metadata"
          repo_name: "metadata"
      - aurelia_v1_tests/run_all:
          name: "history"
          repo_name: "history"
      - aurelia_v1_tests/run_all:
          name: "history-browser"
          repo_name: "history-browser"
      - aurelia_v1_tests/run_all:
          name: "path"
          repo_name: "path"
      - aurelia_v1_tests/run_all:
          name: "http-client"
          repo_name: "http-client"
      - aurelia_v1_tests/run_all:
          name: "loader"
          repo_name: "loader"
      - aurelia_v1_tests/run_all:
          name: "loader-default"
          repo_name: "loader-default"
      - aurelia_v1_tests/run_all:
          name: "event-aggregator"
          repo_name: "event-aggregator"
      - aurelia_v1_tests/run_all:
          name: "task-queue"
          repo_name: "task-queue"
      - aurelia_v1_tests/run_all:
          name: "route-recognizer"
          repo_name: "route-recognizer"
      - aurelia_v1_tests/run_all:
          name: "binding"
          repo_name: "binding"
      - aurelia_v1_tests/run_all:
          name: "templating"
          repo_name: "templating"
      - aurelia_v1_tests/run_all:
          name: "templating-binding"
          repo_name: "templating-binding"
      - aurelia_v1_tests/run_all:
          name: "bootstrapper"
          repo_name: "bootstrapper"
      - aurelia_v1_tests/run_all:
          name: "i18n"
          repo_name: "i18n"
