description: # The purpose of this orb

orbs:
  aurelia_v1_tests:
    executors:
      specialthingsexecutor:
        docker:
          - image: circleci/node:10.12-stretch-browsers
    commands:
      dospecialthings:
        steps:
          - run: echo "We will now do special things"
    jobs:
      myjob:
        executor: specialthingsexecutor
        steps:
          - dospecialthings

version: 2.1
workflows:
  main:
    jobs:
      - aurelia_v1_tests/myjob
