description: # The purpose of this orb

orbs:
  aurelia_v1_tests:
    executors:
      docker_circleci:
        parameters:
          node_version:
            type: string
        docker:
          - image: circleci/node:<<parameters.node_version>>-stretch-browsers
    commands:
      clone_install_build_test:
        parameters:
          repo_name:
            type: string
        steps:
          - run: git clone https://github.com/aurelia/<<parameters.repo_name>>
          - run:
              name: Install
              command: |
                cd <<parameters.repo_name>>
                npm ci
                npm i jspm
                ./node_modules/.bin/jspm install
                ./node_modules/.bin/gulp build
                ./node_modules/.bin/karma start --single-run
                ./node_modules/.bin/gulp prepare-release
    jobs:
      run_all:
        parameters:
          node_version:
            type: string
          repo_name:
            type: string
        executor:
          docker_circleci:
            node_version: <<parameters.node_version>>
        steps:
          - clone_install_build_test:
              repo_name: <<parameters.repo_name>>

version: 2.1
workflows:
  main:
    jobs:
      - aurelia_v1_tests/run_all:
          name: polyfills
          repo_name: polyfills
          node_version: 10.12
