version: 2.1
description: Aurelia v1

orbs:
  common: aurelia/common@volatile

commands:
  install_build_test_gulp:
    parameters:
      test_command:
        type: string
        default: "./node_modules/.bin/karma start --single-run"
      build_command:
        type: string
        default: "./node_modules/.bin/gulp build"
      prepare_release_command:
        type: string
        default: "./node_modules/.bin/gulp prepare-release"
    steps:
      - run:
          name: install
          command: |
            npm ci
            npm i jspm
            ./node_modules/.bin/jspm install
      - run:
          name: test
          command: <<parameters.test_command>>
      - run:
          name: prepare-release
          command: <<parameters.prepare_release_command>>
  install_run_e2e_tests:
    parameters:
      test_repo:
        type: string
        default: "https://github.com/aurelia/e2e-tests"
      registry:
        type: string
        default: "http://localhost:4873"
    steps:
      - run:
          name: Install Chrome
          command: |
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
            sudo apt-get update
            sudo apt-get install google-chrome-stable
      - run:
          name: "install e2e tests"
          command: |
            git clone <<parameters.test_repo>>
            cd e2e-tests
            npm install --registry <<parameters.registry>>
            npm run build
      - run:
          name: "run the unit tests"
          command: |
            cd e2e-tests
            npm run test
      - run:
          name: "serve the test app"
          background: true
          command: |
            cd e2e-tests
            npm run run
      - run:
          name: "run the e2e tests"
          command: |
            cd e2e-tests
            npm run protractor
  merge_and_dist:
    parameters:
      from:
        type: string
      to:
        type: string
      message:
        type: string
        default: "chore(all): add latest build artifacts"
    steps:
      - run: git fetch origin
      - run: git add dist/* --force && git status
      - run: git stash && git status
      - run: git checkout <<parameters.to>> && git status
      - run: git reset --hard origin/<<parameters.to>> && git status
      - run: git merge <<parameters.from>> --no-ff --no-edit -Xtheirs && git status
      - run: rm -rf dist && git status
      - run: git add . && git status
      - run: git checkout stash -- . && git status
      - run: git add dist/* --force && git status
      - run: git add . && git status
      - run: git commit --allow-empty -m "<<parameters.message>>" && git status
      - run: git push origin <<parameters.to>> && git status

jobs:
  build_test_external:
    parameters:
      repo_name:
        type: string
      process:
        type: string
        default: "gulp"
    executor: common/docker_circleci
    steps:
      - run: mkdir <<parameters.repo_name>>
      - common/clone_repo:
          repo_name: <<parameters.repo_name>>
          dir: <<parameters.repo_name>>
      - common/configure_git
      - common/setup_verdaccio
      - install_build_test_gulp
      - common/npm_publish_verdaccio
  build_test:
    parameters:
      process:
        type: string
        default: "gulp"
    executor: common/docker_circleci
    steps:
      - checkout
      - common/configure_git
      - common/setup_verdaccio
      - install_build_test_gulp
      - common/npm_publish_verdaccio
      - install_run_e2e_tests
  build_merge:
    parameters:
      process:
        type: string
        default: "gulp"
      from:
        type: string
        default: "develop"
      to:
        type: string
        default: "master"
      message:
        type: string
        default: "chore(all): add latest build artifacts"
    executor: common/docker_circleci
    steps:
      - checkout
      - common/configure_git
      - install_build_test_gulp
      - merge_and_dist:
          from: <<parameters.from>>
          to: <<parameters.to>>
          message: <<parameters.message>>
  merge_back:
    parameters:
      from:
        type: string
        default: "master"
      to:
        type: string
        default: "develop"
      message:
        type: string
        default: "chore(all): merge latest release"
    executor: common/docker_circleci
    steps:
      - checkout
      - common/configure_git
      - run: git fetch origin
      - run: git checkout <<parameters.to>> && git status
      - run: git reset --hard origin/<<parameters.to>> && git status
      - run: git merge <<parameters.from>> --squash && git status
      - run: git reset HEAD dist
      - run: git commit --allow-empty -m "<<parameters.message>>" && git status
      - run: git push origin <<parameters.to>> && git status
  npm_publish:
    parameters:
      tag:
        type: string
        default: "latest"
      args:
        type: string
        default: ""
    executor: common/docker_circleci
    steps:
      - checkout
      - common/configure_git
      - run:
          name: "Authenticate with registry"
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish --tag <<parameters.tag>> <<parameters.args>>