version: 2.1
description: Aurelia v1

orbs:
  common: aurelia/common@volatile

commands:
  install_build_test_gulp:
    parameters:
      test_command:
        type: string
        default: "./node_modules/.bin/karma start --single-run"
      build_command:
        type: string
        default: "./node_modules/.bin/gulp build"
      prepare_release_command:
        type: string
        default: "./node_modules/.bin/gulp prepare-release"
    steps:
      - run:
          name: install
          command: |
            npm ci
            npm i jspm
            ./node_modules/.bin/jspm install
      - run:
          name: test
          command: <<parameters.test_command>>
      - run:
          name: build
          command: <<parameters.build_command>>
      - run:
          name: prepare-release
          command: <<parameters.prepare_release_command>>
  install_run_e2e_tests:
    parameters:
      test_repo:
        type: string
        default: "https://github.com/aurelia/e2e-tests"
      registry:
        type: string
        default: "http://localhost:4873"
    steps:
      - run:
          name: "install e2e tests"
          command: |
            git clone <<parameters.test_repo>>
            cd e2e-tests
            npm install --registry <<parameters.registry>>
            npm run build
      - run:
          name: "run the unit tests"
          command: |
            cd e2e-tests
            npm run test
      - run:
          name: "serve the test app"
          background: true
          command: |
            cd e2e-tests
            npm run run
      - run:
          name: "run the e2e tests"
          command: |
            cd e2e-tests
            npm run protractor
jobs:
  run_all:
    parameters:
      repo_name:
        type: string
      process:
        type: string
    executor: common/docker_circleci
    steps:
      - common/clone_repo:
          repo_name: <<parameters.repo_name>>
      - install_build_test_gulp