version: 2.1
description: Aurelia v1

orbs:
  common: aurelia/common@volatile

commands:
  install_build_test_gulp:
    steps:
      - run:
          name: install
          command: |
            npm ci
            npm i jspm
            ./node_modules/.bin/jspm install
      - run:
          name: test
          command: ./node_modules/.bin/karma start --single-run
      - run:
          name: build
          command: ./node_modules/.bin/gulp build
      - run:
          name: prepare-release
          command: ./node_modules/.bin/gulp prepare-release
  install_run_e2e_tests:
    parameters:
      registry:
        type: string
        default: "http://localhost:4873"
    steps:
      - run:
          name: "install and run e2e tests"
          command: |
            git clone https://github.com/aurelia/e2e-tests
            cd e2e-tests
            npm install --registry <<parameters.registry>>
            npm run build
            npm run test
            npm run protractor
jobs:
  run_all:
    parameters:
      repo_name:
        type: string
      process:
        type: string
    executor: common/docker_circleci
    steps:
      - common/clone_repo:
          repo_name: <<parameters.repo_name>>
      - install_build_test_gulp